INSERT INTO pets (name, type, breed, age, weight_lbs, description, image_url) VALUES
-- Dogs (35)
('Buddy',    'dog', 'Golden Retriever',   4,  65,  'Loves long walks and belly rubs.',            '/images/pets/default.jpg'),
('Max',      'dog', 'Labrador',           3,  72,  'Friendly with kids and other pets.',           '/images/pets/default.jpg'),
('Charlie',  'dog', 'Beagle',             5,  22,  'Energetic and always ready to play.',          '/images/pets/default.jpg'),
('Cooper',   'dog', 'German Shepherd',    2,  68,  'Sweet-natured and easy to train.',             '/images/pets/default.jpg'),
('Milo',     'dog', 'Poodle',             6,  55,  'Calm and gentle, great for apartment life.',   '/images/pets/default.jpg'),
('Teddy',    'dog', 'Shih Tzu',           4,  12,  'Playful and mischievous.',                     '/images/pets/default.jpg'),
('Rocky',    'dog', 'Boxer',              3,  70,  'Loyal companion who loves cuddles.',           '/images/pets/default.jpg'),
('Bear',     'dog', 'Husky',              7,  52,  'Quiet and observant, loves a cozy spot.',      '/images/pets/default.jpg'),
('Duke',     'dog', 'Bulldog',            5,  50,  'Curious explorer who loves attention.',        '/images/pets/default.jpg'),
('Zeus',     'dog', 'Border Collie',      2,  42,  'Energetic and always ready to play.',          '/images/pets/default.jpg'),
('Bella',    'dog', 'Golden Retriever',   1,  58,  'Friendly with kids and other pets.',           '/images/pets/default.jpg'),
('Luna',     'dog', 'Labrador',           3,  68,  'Loves long walks and belly rubs.',             '/images/pets/default.jpg'),
('Daisy',    'dog', 'Beagle',             4,  20,  'Playful and food-motivated.',                  '/images/pets/daisy.jpg'),
('Molly',    'dog', 'Corgi',              2,  28,  'Sweet-natured and easy to train.',             '/images/pets/default.jpg'),
('Sadie',    'dog', 'Pug',               6,  18,  'Calm and gentle, great for apartment life.',   '/images/pets/default.jpg'),
('Maggie',   'dog', 'Dachshund',          3,  11,  'Curious explorer who loves attention.',        '/images/pets/default.jpg'),
('Lola',     'dog', 'Maltese',            5,   6,  'Playful and mischievous.',                     '/images/pets/default.jpg'),
('Sophie',   'dog', 'Poodle',             4,  50,  'Loyal companion who loves cuddles.',           '/images/pets/default.jpg'),
('Chloe',    'dog', 'Chihuahua',          2,   5,  'Quiet and observant, loves a cozy spot.',      '/images/pets/default.jpg'),
('Lucy',     'dog', 'Cavalier',           7,  18,  'Independent but very affectionate.',           '/images/pets/default.jpg'),
('Bentley',  'dog', 'German Shepherd',    3,  75,  'Loves long walks and belly rubs.',             '/images/pets/default.jpg'),
('Gus',      'dog', 'Labrador',           5,  80,  'Friendly with kids and other pets.',           '/images/pets/default.jpg'),
('Archie',   'dog', 'Golden Retriever',   1,  60,  'Energetic and always ready to play.',          '/images/pets/default.jpg'),
('Tucker',   'dog', 'Boxer',              4,  65,  'Sweet-natured and easy to train.',             '/images/pets/default.jpg'),
('Oscar',    'dog', 'Husky',              6,  48,  'Calm and gentle, great for apartment life.',   '/images/pets/default.jpg'),
('Finn',     'dog', 'Border Collie',      2,  38,  'Playful and mischievous.',                     '/images/pets/default.jpg'),
('Winston',  'dog', 'Bulldog',            8,  53,  'Loyal companion who loves cuddles.',           '/images/pets/default.jpg'),
('Hank',     'dog', 'Dachshund',          3,  12,  'Curious explorer who loves attention.',        '/images/pets/default.jpg'),
('Leo',      'dog', 'Pug',               5,  20,  'Quiet and observant, loves a cozy spot.',      '/images/pets/default.jpg'),
('Louie',    'dog', 'Shih Tzu',           4,  11,  'Independent but very affectionate.',           '/images/pets/default.jpg'),
('Biscuit',  'dog', 'Corgi',              2,  30,  'Loves long walks and belly rubs.',             '/images/pets/default.jpg'),
('Pepper',   'dog', 'Chihuahua',          3,   5,  'Friendly with kids and other pets.',           '/images/pets/default.jpg'),
('Ranger',   'dog', 'Labrador',           6,  78,  'Energetic and always ready to play.',          '/images/pets/default.jpg'),
('Scout',    'dog', 'Beagle',             4,  23,  'Sweet-natured and easy to train.',             '/images/pets/default.jpg'),
('Bruno',    'dog', 'German Shepherd',    5,  88,  'Calm and gentle, great for apartment life.',   '/images/pets/default.jpg'),

-- Cats (30)
('Mittens',  'cat', 'Domestic Shorthair', 2,   8,  'Curious and affectionate.',                    '/images/pets/mittens.jpg'),
('Oliver',   'cat', 'Siamese',            4,   9,  'Independent but very affectionate.',           '/images/pets/default.jpg'),
('Mochi',    'cat', 'Persian',            3,  10,  'Calm and gentle, great for apartment life.',   '/images/pets/default.jpg'),
('Salem',    'cat', 'Domestic Shorthair', 6,   9,  'Quiet and observant, loves a cozy spot.',      '/images/pets/default.jpg'),
('Simba',    'cat', 'Maine Coon',         5,  16,  'Playful and mischievous.',                     '/images/pets/default.jpg'),
('Nala',     'cat', 'Bengal',             2,  11,  'Energetic and always ready to play.',          '/images/pets/default.jpg'),
('Tiger',    'cat', 'Domestic Shorthair', 7,   9,  'Friendly with kids and other pets.',           '/images/pets/default.jpg'),
('Shadow',   'cat', 'Russian Blue',       4,  10,  'Curious explorer who loves attention.',        '/images/pets/default.jpg'),
('Ginger',   'cat', 'Abyssinian',         3,   8,  'Loyal companion who loves cuddles.',           '/images/pets/default.jpg'),
('Felix',    'cat', 'Ragdoll',            5,  15,  'Sweet-natured and easy to train.',             '/images/pets/default.jpg'),
('Pumpkin',  'cat', 'Scottish Fold',      1,   7,  'Loves long walks and belly rubs.',             '/images/pets/default.jpg'),
('Cleo',     'cat', 'Sphynx',             6,   9,  'Independent but very affectionate.',           '/images/pets/default.jpg'),
('Jasper',   'cat', 'Maine Coon',         4,  18,  'Calm and gentle, great for apartment life.',   '/images/pets/default.jpg'),
('Willow',   'cat', 'Siamese',            2,   8,  'Quiet and observant, loves a cozy spot.',      '/images/pets/default.jpg'),
('Ash',      'cat', 'Russian Blue',       3,  11,  'Playful and mischievous.',                     '/images/pets/default.jpg'),
('Onyx',     'cat', 'Domestic Shorthair', 5,  10,  'Curious explorer who loves attention.',        '/images/pets/default.jpg'),
('Hazel',    'cat', 'Bengal',             4,  12,  'Energetic and always ready to play.',          '/images/pets/default.jpg'),
('Mocha',    'cat', 'Abyssinian',         2,   8,  'Friendly with kids and other pets.',           '/images/pets/default.jpg'),
('Coco',     'cat', 'Persian',            6,  11,  'Loyal companion who loves cuddles.',           '/images/pets/default.jpg'),
('Boo',      'cat', 'Ragdoll',            3,  14,  'Sweet-natured and easy to train.',             '/images/pets/default.jpg'),
('Maple',    'cat', 'Scottish Fold',      5,   9,  'Curious and affectionate.',                    '/images/pets/default.jpg'),
('Marble',   'cat', 'Domestic Shorthair', 1,   7,  'Independent but very affectionate.',           '/images/pets/default.jpg'),
('Tuxedo',   'cat', 'Domestic Shorthair', 4,  10,  'Calm and gentle, great for apartment life.',   '/images/pets/default.jpg'),
('Luna',     'cat', 'Siamese',            7,   9,  'Quiet and observant, loves a cozy spot.',      '/images/pets/default.jpg'),
('Pearl',    'cat', 'Persian',            3,  10,  'Playful and mischievous.',                     '/images/pets/default.jpg'),
('Slate',    'cat', 'Russian Blue',       5,  11,  'Curious explorer who loves attention.',        '/images/pets/default.jpg'),
('Ivy',      'cat', 'Bengal',             2,  10,  'Loyal companion who loves cuddles.',           '/images/pets/default.jpg'),
('Cosmo',    'cat', 'Maine Coon',         6,  17,  'Friendly with kids and other pets.',           '/images/pets/default.jpg'),
('Pip',      'cat', 'Abyssinian',         1,   7,  'Energetic and always ready to play.',          '/images/pets/default.jpg'),
('Rue',      'cat', 'Sphynx',             4,   8,  'Sweet-natured and easy to train.',             '/images/pets/default.jpg'),

-- Rabbits (15)
('Clover',      'rabbit', 'Mini Rex',          1,   3,  'Gentle and quiet.',                             '/images/pets/default.jpg'),
('Snowball',    'rabbit', 'Netherland Dwarf',  2,   2,  'Independent but very affectionate.',            '/images/pets/default.jpg'),
('Oreo',        'rabbit', 'Holland Lop',       3,   4,  'Calm and gentle, great for apartment life.',    '/images/pets/default.jpg'),
('Caramel',     'rabbit', 'Lionhead',          1,   3,  'Curious explorer who loves attention.',         '/images/pets/default.jpg'),
('Pebble',      'rabbit', 'Flemish Giant',     4,  14,  'Quiet and observant, loves a cozy spot.',       '/images/pets/default.jpg'),
('Fern',        'rabbit', 'Dutch',             2,   5,  'Playful and mischievous.',                      '/images/pets/default.jpg'),
('Bun',         'rabbit', 'Angora',            3,   6,  'Loyal companion who loves cuddles.',            '/images/pets/default.jpg'),
('Marshmallow', 'rabbit', 'Mini Rex',          1,   3,  'Sweet-natured and easy to train.',              '/images/pets/default.jpg'),
('Maple',       'rabbit', 'Holland Lop',       2,   4,  'Gentle and quiet.',                             '/images/pets/default.jpg'),
('Cinnamon',    'rabbit', 'Netherland Dwarf',  3,   2,  'Friendly with kids and other pets.',            '/images/pets/default.jpg'),
('Dusty',       'rabbit', 'Lionhead',          1,   3,  'Independent but very affectionate.',            '/images/pets/default.jpg'),
('Oat',         'rabbit', 'Flemish Giant',     4,  13,  'Calm and gentle, great for apartment life.',    '/images/pets/default.jpg'),
('Thistle',     'rabbit', 'Dutch',             2,   5,  'Curious explorer who loves attention.',         '/images/pets/default.jpg'),
('Acorn',       'rabbit', 'Angora',            3,   6,  'Quiet and observant, loves a cozy spot.',       '/images/pets/default.jpg'),
('Cotton',      'rabbit', 'Mini Rex',          1,   3,  'Playful and mischievous.',                      '/images/pets/default.jpg'),

-- Birds (12)
('Sunny',     'bird', 'Cockatiel',    5,   1,  'Social and chatty.',                            '/images/pets/sunny.jpg'),
('Kiwi',      'bird', 'Parakeet',     3,   1,  'Energetic and always ready to play.',           '/images/pets/default.jpg'),
('Mango',     'bird', 'Lovebird',     4,   1,  'Friendly with kids and other pets.',            '/images/pets/default.jpg'),
('Rio',       'bird', 'Conure',       2,   2,  'Independent but very affectionate.',            '/images/pets/default.jpg'),
('Azure',     'bird', 'African Grey', 8,   1,  'Calm and gentle, great for apartment life.',   '/images/pets/default.jpg'),
('Cobalt',    'bird', 'Parakeet',     2,   1,  'Quiet and observant, loves a cozy spot.',      '/images/pets/default.jpg'),
('Tango',     'bird', 'Conure',       3,   2,  'Playful and mischievous.',                     '/images/pets/default.jpg'),
('Pippin',    'bird', 'Cockatiel',    6,   1,  'Loyal companion who loves cuddles.',           '/images/pets/default.jpg'),
('Coral',     'bird', 'Lovebird',     1,   1,  'Curious explorer who loves attention.',        '/images/pets/default.jpg'),
('Sky',       'bird', 'Finch',        2,   1,  'Sweet-natured and easy to train.',             '/images/pets/default.jpg'),
('Pistachio', 'bird', 'African Grey', 7,   1,  'Social and chatty.',                           '/images/pets/default.jpg'),
('Zephyr',    'bird', 'Cockatoo',     5,   2,  'Energetic and always ready to play.',          '/images/pets/default.jpg'),

-- Reptiles (8)
('Draco',  'reptile', 'Bearded Dragon',     3,   1,  'Calm and observant, loves basking.',           '/images/pets/default.jpg'),
('Spike',  'reptile', 'Leopard Gecko',      2,   1,  'Easy to handle and low-maintenance.',          '/images/pets/default.jpg'),
('Ember',  'reptile', 'Bearded Dragon',     4,   1,  'Curious and responsive to handling.',          '/images/pets/default.jpg'),
('Zigzag', 'reptile', 'Crested Gecko',      1,   1,  'Gentle and great for beginners.',              '/images/pets/default.jpg'),
('Scales', 'reptile', 'Ball Python',        5,   4,  'Docile and easy to care for.',                 '/images/pets/default.jpg'),
('Jasper', 'reptile', 'Blue-Tongued Skink', 3,   1,  'Friendly and curious.',                        '/images/pets/default.jpg'),
('Onyx',   'reptile', 'Ball Python',        6,   5,  'Calm and low-maintenance.',                    '/images/pets/default.jpg'),
('Verde',  'reptile', 'Crested Gecko',      2,   1,  'Active and loves to climb.',                   '/images/pets/default.jpg');
